// Realistic demo wardrobe used to seed new sessions (Feature 2).
export const DEMO_WARDROBE = [
  {
    id: 'demo-1',
    name: 'Classic White Tee',
    category: 'T-Shirt',
    color: 'White',
    season: 'Summer',
    image: '/wardrobe/white-tshirt.png',
  },
  {
    id: 'demo-2',
    name: 'Breton Striped Shirt',
    category: 'Shirt',
    color: 'Navy',
    season: 'Spring',
    image: '/wardrobe/striped-shirt.png',
  },
  {
    id: 'demo-3',
    name: 'Essential Black Hoodie',
    category: 'Hoodie',
    color: 'Black',
    season: 'Fall',
    image: '/wardrobe/black-hoodie.png',
  },
  {
    id: 'demo-4',
    name: 'Oatmeal Knit Sweater',
    category: 'Sweater',
    color: 'Beige',
    season: 'Winter',
    image: '/wardrobe/beige-sweater.png',
  },
  {
    id: 'demo-5',
    name: 'Slim Blue Jeans',
    category: 'Jeans',
    color: 'Blue',
    season: 'All Season',
    image: '/wardrobe/blue-jeans.png',
  },
  {
    id: 'demo-6',
    name: 'Olive Chino Pants',
    category: 'Pants',
    color: 'Olive',
    season: 'Fall',
    image: '/wardrobe/olive-chinos.png',
  },
  {
    id: 'demo-7',
    name: 'Minimal White Sneakers',
    category: 'Sneakers',
    color: 'White',
    season: 'All Season',
    image: '/wardrobe/white-sneakers.png',
  },
  {
    id: 'demo-8',
    name: 'Brown Chelsea Boots',
    category: 'Boots',
    color: 'Brown',
    season: 'Winter',
    image: '/wardrobe/brown-boots.png',
  },
  {
    id: 'demo-9',
    name: 'Heritage Trench Coat',
    category: 'Jacket',
    color: 'Beige',
    season: 'Fall',
    image: '/wardrobe/beige-trench.png',
  },
  {
    id: 'demo-10',
    name: 'Vintage Denim Jacket',
    category: 'Jacket',
    color: 'Blue',
    season: 'Spring',
    image: '/wardrobe/denim-jacket.png',
  },
  {
    id: 'demo-11',
    name: 'Acetate Sunglasses',
    category: 'Accessories',
    color: 'Black',
    season: 'Summer',
    image: '/wardrobe/sunglasses.png',
  },
]
